'use strict'
module.exports = {
  Door: true,
  homepage: false,
  conference: false,
  BASE_ISTRUE: true,
  loginShow: false,
  signupShow: false,
  stageLink: true,
  signPdf: true,
  empLogin: true,
  empPwdShow: true,
  empActiveShow: true,
  empPhoneCheck: true,
  empWorkNoCheck: false,
  workbayCheck: false,
  agentShow: true,
  agentCheck: true,
  isChangeXSS: true,
  empComShow: true,
  addAreaIsShow: false,
  addAreaCloseIsShow: true,
  whiteListShow: false,
  doorGate: false,
  dataError: false,
  deptNoShow: false,
  takePhotoShow: false,
  vTypeShow: true,
  sendSmsType: 2, //0手机号1邮箱2手机号和邮箱二选一
  smsDetailShow: true,
  footerEmpClose: false,
  SSLValue: true,
  customTemplateShow: true,
  papernew: true,
  visitAvatarRequired: false,
  idCardNum: 1,
  photoShow: false,
  comAddEmpShow: true,
  printType: 0,//0新贴纸1旧贴纸
  empNoSearchShow: false,
  getEmpByEmpName: false,
  empTotal: true,
  operatorSet: false,
  departVnoSet: false,
  onworkManager: false,//加班管理人
  defaultInterviewSet: false,//加班管理人
  tableFormShow: true,
  approveIsMore: true,
  BASE_API: '"http://www.coolvisit.top/qcvisitBase"',//'"http://visit.eastech.com/qcvisit"',//
  BASE_LINK: '"http://www.coolvisit.top/"',//'"http://visit.eastech.com/"',//
  BASE_VERSION: '"v2.3.0"',
  HOST: '"www.coolvisit.top"'//'"visit.eastech.com"'
}