'use strict'
module.exports = {
  Door: true,
  homepage: false,
  conference: false,
  BASE_ISTRUE: false,
  loginShow: false,
  signupShow: false,//注册显示
  stageLink: true,//前台跳转
  signPdf: true,//安全协议
  empLogin: true,//员工登录
  empPwdShow: true,//员工密码显示
  empActiveShow: true,//员工激活显示
  empPhoneCheck: true,//员工手机号强制检测
  empWorkNoCheck: false,//员工工号强制检测
  workbayCheck: false,
  agentShow: true,
  agentCheck: true,
  isChangeXSS: true,
  empComShow: true,
  addAreaIsShow: false,
  addAreaCloseIsShow: true,
  whiteListShow: false,
  doorGate: false,
  dataError: false,
  deptNoShow: false,
  takePhotoShow: false,
  vTypeShow: true,
  sendSmsType: 2, //0手机号1邮箱2手机号和邮箱二选一
  smsDetailShow: true,
  footerEmpClose: false,
  SSLValue: true,
  customTemplateShow: true,
  papernew: true,
  visitAvatarRequired: false,
  idCardNum: 0,
  photoShow: false,
  comAddEmpShow: true,
  printType: 0,//0新贴纸1旧贴纸
  empNoSearchShow: false,
  getEmpByEmpName: false,
  empTotal: true,
  operatorSet: false,
  departVnoSet: false,
  onworkManager: false,//加班管理人
  defaultInterviewSet: false,//加班管理人
  tableFormShow: true,
  approveIsMore: true,
  defaultVsetIsDisplayShow: true,
  checkPassword: true,
  extendShow: true,
  extendExportShow: true,
  calendarShow: false,
  calendarLRShow: false,
  empSendComRequired: true,
  openStatusShow: true,//访客记录openstatus
  BASE_API: '"http://www.coolvisit.top/qcvisitBase"',//'"http://visit.eastech.com/qcvisit"',//
  BASE_LINK: '"http://www.coolvisit.top/"',//'"http://visit.eastech.com/"',//
  BASE_VERSION: '"v2.3.1"',
  HOST: '"www.coolvisit.top"'//'"visit.eastech.com"'
}