'use strict'
module.exports = {
  Door: true,
  homepage: false,
  signupShow: true,
  conference: false,
  BASE_ISTRUE: false,
  loginShow: false,
  signupShow: false,
  stageLink: true,
  signPdf: true,
  empLogin: true,
  empPwdShow: false,
  empActiveShow: true,
  empPhoneCheck: true,
  empWorkNoCheck: false,
  workbayCheck: false,
  agentShow: false,
  agentCheck: false,
  isChangeXSS: true,
  empComShow: true,
  addAreaIsShow: false,
  addAreaCloseIsShow: true,
  whiteListShow: false,
  doorGate: false,
  dataError: false,
  deptNoShow: false,
  takePhotoShow: false,
  vTypeShow: false,
  sendSmsType: 2, //0手机号1邮箱2手机号和邮箱二选一
  areaEquipShow: true,//网安中心区域设备配置
  wazxFlag: true,
  firstAndLastRoomTime: true,
  keyListExport: true,
  checkPassword: true,
  BASE_API: '"http://www.coolvisit.top/qcvisit"',//'"http://120.79.239.109/qcvisit"',//
  BASE_LINK: '"http://www.coolvisit.top/wazx/"',//'"http://120.79.239.109/"',//
  BASE_VERSION: '"v2.2.3"',
  HOST: '"www.coolvisit.top"'//'"120.79.239.109"'
}