export { default as equipGroup } from './equipGroup'
export { default as equipDetail } from './equipDetail'
export { default as equipList } from './equipList'
export { default as detail } from './detail'
export { default as record } from './record'